"""Seed question bank: per-domain questions with difficulty and round types.

Each entry: (domain_name, question_type, difficulty, text, options, correct_answer, skill_tags)
- options: list of "A. ..." style choices (only for mcq) or None
- correct_answer: option letter for mcq, or model answer text for others (optional)
"""

QUESTION_BANK = [
    # ---------- Programming ----------
    ("Programming", "mcq", "easy",
     "What is the time complexity of binary search on a sorted array of n elements?",
     ["A. O(1)", "B. O(log n)", "C. O(n)", "D. O(n log n)"], "B",
     ["Algorithms", "Complexity Analysis"]),
    ("Programming", "mcq", "medium",
     "Which data structure gives O(1) amortized insertion at both ends?",
     ["A. Array", "B. Stack", "C. Deque", "D. Linked List"], "C",
     ["Data Structures", "Deque"]),
    ("Programming", "theory", "easy",
     "Explain the difference between an array and a linked list.",
     None, None, ["Data Structures"]),
    ("Programming", "theory", "medium",
     "Explain the difference between depth-first search and breadth-first search. When would you prefer one over the other?",
     None, None, ["Algorithms", "Graph"]),
    ("Programming", "coding", "easy",
     "Write a function that checks whether a given string is a palindrome.",
     None, None, ["Algorithms", "Strings"]),
    ("Programming", "coding", "medium",
     "Write a function to reverse a linked list iteratively.",
     None, None, ["Data Structures", "Linked List"]),
    ("Programming", "scenario", "medium",
     "Your application is too slow and profiling shows most time is spent on a hot loop. Walk me through how you would optimize it.",
     None, None, ["Performance", "Optimization"]),
    ("Programming", "rapid_fire", "easy",
     "What is a stack? Name its operations.",
     None, None, ["Data Structures"]),

    # ---------- Python ----------
    ("Python", "mcq", "easy",
     "Which keyword is used to define a function in Python?",
     ["A. func", "B. define", "C. def", "D. function"], "C", ["Python"]),
    ("Python", "mcq", "medium",
     "What does the `yield` keyword do inside a Python function?",
     ["A. Stops the function forever", "B. Returns a value and resumes on next call, creating a generator",
      "C. Raises an exception", "D. Exits the interpreter"], "B",
     ["Python", "Generators"]),
    ("Python", "mcq", "hard",
     "What is the output of `[x**2 for x in range(4) if x % 2 == 0]`?",
     ["A. [0, 4, 16]", "B. [0, 4]", "C. [1, 9]", "D. [0, 1, 4, 9]"], "B",
     ["Python", "Comprehensions"]),
    ("Python", "theory", "medium",
     "Explain the difference between a list and a tuple in Python, and when each is preferable.",
     None, None, ["Python"]),
    ("Python", "coding", "medium",
     "Write a Python decorator that measures and prints the execution time of a function.",
     None, None, ["Python", "Decorators"]),
    ("Python", "rapid_fire", "easy",
     "What is the difference between `==` and `is` in Python?",
     None, None, ["Python"]),

    # ---------- C++ ----------
    ("C++", "mcq", "medium",
     "Which of the following is true about a virtual destructor in C++?",
     ["A. It is required only for abstract classes", "B. It ensures derived class destructors run when deleting via base pointer",
      "C. It cannot be private", "D. It makes the class non-polymorphic"], "B",
     ["C++", "OOP"]),
    ("C++", "mcq", "hard",
     "What is the output of `sizeof(int*)` on a 64-bit system?",
     ["A. 4", "B. 8", "C. 16", "D. Undefined"], "B", ["C++", "Pointers"]),
    ("C++", "theory", "medium",
     "Explain the difference between `new`/`delete` and `malloc`/`free` in C++.",
     None, None, ["C++", "Memory Management"]),
    ("C++", "coding", "easy",
     "Write a C++ function that swaps two integers using references.",
     None, None, ["C++", "References"]),

    # ---------- Java ----------
    ("Java", "mcq", "easy",
     "Which of these is the entry point of a Java program?",
     ["A. main()", "B. start()", "C. run()", "D. init()"], "A", ["Java"]),
    ("Java", "mcq", "medium",
     "What happens when the JVM runs out of heap memory?",
     ["A. It crashes silently", "B. It throws OutOfMemoryError",
      "C. It deletes unused objects automatically", "D. It restarts"], "B",
     ["Java", "JVM"]),
    ("Java", "theory", "medium",
     "Explain the difference between an abstract class and an interface in Java.",
     None, None, ["Java", "OOP"]),

    # ---------- SQL ----------
    ("SQL", "mcq", "easy",
     "Which SQL clause is used to filter rows?",
     ["A. ORDER BY", "B. GROUP BY", "C. WHERE", "D. HAVING"], "C", ["SQL"]),
    ("SQL", "mcq", "medium",
     "Which SQL statement removes a table and its structure entirely?",
     ["A. DELETE", "B. TRUNCATE", "C. DROP", "D. REMOVE"], "C", ["SQL", "DDL"]),
    ("SQL", "mcq", "hard",
     "Given tables `employees(id, dept_id, salary)`, which query returns departments with average salary above 50000?",
     ["A. SELECT dept_id FROM employees WHERE AVG(salary)>50000",
      "B. SELECT dept_id FROM employees GROUP BY dept_id HAVING AVG(salary)>50000",
      "C. SELECT dept_id FROM employees GROUP BY salary HAVING AVG(salary)>50000",
      "D. SELECT dept_id FROM employees WHERE salary>50000 GROUP BY dept_id"], "B",
     ["SQL", "Aggregation"]),
    ("SQL", "theory", "easy",
     "Explain the difference between an INNER JOIN and a LEFT JOIN.",
     None, None, ["SQL", "Joins"]),
    ("SQL", "coding", "medium",
     "Write a SQL query to find the second-highest salary from an employees table.",
     None, None, ["SQL"]),

    # ---------- DBMS ----------
    ("DBMS", "mcq", "medium",
     "Which ACID property ensures a transaction is all-or-nothing?",
     ["A. Atomicity", "B. Consistency", "C. Isolation", "D. Durability"], "A", ["DBMS", "ACID"]),
    ("DBMS", "mcq", "hard",
     "What problem do indexes primarily solve in a database?",
     ["A. Prevent deadlocks", "B. Speed up data retrieval",
      "C. Enforce referential integrity", "D. Reduce storage"], "B",
     ["DBMS", "Indexing"]),
    ("DBMS", "theory", "medium",
     "Explain 1NF, 2NF and 3NF with a simple example.",
     None, None, ["DBMS", "Normalization"]),

    # ---------- Operating Systems ----------
    ("Operating Systems", "mcq", "easy",
     "Which component of the OS manages process scheduling?",
     ["A. Compiler", "B. Scheduler", "C. Linker", "D. Loader"], "B", ["Operating Systems"]),
    ("Operating Systems", "mcq", "medium",
     "What is a deadlock in an operating system?",
     ["A. A process that never terminates",
      "B. A set of processes each waiting for resources held by another in a cycle",
      "C. An infinite loop in user code", "D. A kernel panic"], "B",
     ["Operating Systems", "Deadlock"]),
    ("Operating Systems", "theory", "medium",
     "Explain the difference between a process and a thread.",
     None, None, ["Operating Systems", "Processes", "Threads"]),

    # ---------- Computer Networks ----------
    ("Computer Networks", "mcq", "easy",
     "Which protocol is used to resolve domain names to IP addresses?",
     ["A. HTTP", "B. FTP", "C. DNS", "D. SMTP"], "C", ["Computer Networks", "DNS"]),
    ("Computer Networks", "mcq", "medium",
     "In the TCP/IP model, which layer is responsible for routing packets?",
     ["A. Application", "B. Transport", "C. Network", "D. Physical"], "C",
     ["Computer Networks", "TCP/IP"]),
    ("Computer Networks", "theory", "medium",
     "Explain the difference between TCP and UDP. When would you use each?",
     None, None, ["Computer Networks", "TCP", "UDP"]),

    # ---------- Machine Learning ----------
    ("Machine Learning", "mcq", "medium",
     "Which metric is most appropriate for evaluating an imbalanced binary classification problem?",
     ["A. Accuracy", "B. F1-score", "C. Mean Squared Error", "D. R-squared"], "B",
     ["Machine Learning", "Model Evaluation"]),
    ("Machine Learning", "mcq", "medium",
     "What is overfitting in machine learning?",
     ["A. The model performs well on new data",
      "B. The model learns the training data too well and generalizes poorly",
      "C. The model trains too slowly", "D. The model uses too many GPUs"], "B",
     ["Machine Learning"]),
    ("Machine Learning", "theory", "medium",
     "Explain the bias-variance tradeoff with a simple example.",
     None, None, ["Machine Learning"]),
    ("Machine Learning", "coding", "medium",
     "Using scikit-learn, write the key steps to train and evaluate a logistic regression model on a training/test split.",
     None, None, ["Machine Learning", "Scikit-Learn"]),

    # ---------- Deep Learning ----------
    ("Deep Learning", "mcq", "easy",
     "Which activation function is commonly used in the output layer for binary classification?",
     ["A. ReLU", "B. Sigmoid", "C. Tanh", "D. Leaky ReLU"], "B",
     ["Deep Learning", "Neural Networks"]),
    ("Deep Learning", "mcq", "medium",
     "What does the learning rate control during training?",
     ["A. The size of the network", "B. The step size of weight updates",
      "C. The number of epochs", "D. The batch size"], "B",
     ["Deep Learning", "Training"]),
    ("Deep Learning", "theory", "hard",
     "Explain how backpropagation computes gradients, and the role of the chain rule.",
     None, None, ["Deep Learning", "Backpropagation"]),

    # ---------- React ----------
    ("React", "mcq", "medium",
     "Which hook is used to manage local state in a functional React component?",
     ["A. useEffect", "B. useState", "C. useContext", "D. useRef"], "B", ["React", "Hooks"]),
    ("React", "mcq", "hard",
     "What is the purpose of React.memo?",
     ["A. Memoize a value", "B. Memoize a component to skip re-renders when props are unchanged",
      "C. Cache API responses", "D. Store state persistently"], "B",
     ["React", "Performance"]),
    ("React", "theory", "medium",
     "Explain the difference between props and state in React.",
     None, None, ["React"]),

    # ---------- Node.js ----------
    ("Node.js", "mcq", "easy",
     "Which statement is true about Node.js?",
     ["A. It is single-threaded by default for JS execution",
      "B. It is multi-threaded for all operations",
      "C. It cannot perform I/O", "D. It only runs in browsers"], "A",
     ["Node.js", "Event Loop"]),
    ("Node.js", "theory", "medium",
     "Explain how the Node.js event loop works, including the microtask and macrotask queues.",
     None, None, ["Node.js", "Event Loop"]),

    # ---------- DevOps ----------
    ("DevOps", "mcq", "easy",
     "Which tool is used to containerize applications?",
     ["A. Jenkins", "B. Docker", "C. Git", "D. Ansible"], "B", ["DevOps", "Docker"]),
    ("DevOps", "mcq", "medium",
     "What is the purpose of CI/CD in DevOps?",
     ["A. To manually deploy every release",
      "B. To automate building, testing, and deploying code changes",
      "C. To rewrite the codebase", "D. To monitor user behavior"], "B",
     ["DevOps", "CI/CD"]),
    ("DevOps", "theory", "medium",
     "Explain the difference between Docker and Kubernetes.",
     None, None, ["DevOps", "Docker", "Kubernetes"]),

    # ---------- Cloud ----------
    ("Cloud", "mcq", "easy",
     "Which cloud service model provides virtual machines and infrastructure?",
     ["A. SaaS", "B. PaaS", "C. IaaS", "D. FaaS"], "C", ["Cloud"]),
    ("Cloud", "mcq", "medium",
     "What does 'serverless' mean in cloud computing?",
     ["A. No servers exist in the cloud",
      "B. The provider manages infrastructure while you run code on demand",
      "C. Servers are hidden in a data center", "D. You must manage all servers yourself"], "B",
     ["Cloud", "Serverless"]),

    # ---------- Data Science ----------
    ("Data Science", "mcq", "easy",
     "Which library is most commonly used for data manipulation in Python?",
     ["A. Matplotlib", "B. Pandas", "C. Flask", "D. Requests"], "B",
     ["Data Science", "Pandas"]),
    ("Data Science", "mcq", "medium",
     "What does a p-value of 0.03 indicate in a hypothesis test at a 0.05 significance level?",
     ["A. Reject the null hypothesis", "B. Fail to reject the null hypothesis",
      "C. The test is invalid", "D. The sample size is too small"], "A",
     ["Data Science", "Statistics"]),
    ("Data Science", "theory", "medium",
     "Explain the difference between correlation and causation, with an example.",
     None, None, ["Data Science", "Statistics"]),

    # ---------- Cybersecurity ----------
    ("Cybersecurity", "mcq", "easy",
     "Which of the following is a common web application vulnerability?",
     ["A. SQL Injection", "B. TCP Handshake", "C. DNS Caching", "D. Load Balancing"], "A",
     ["Cybersecurity"]),
    ("Cybersecurity", "mcq", "medium",
     "What does HTTPS add compared to HTTP?",
     ["A. Faster response times", "B. Encrypted communication via TLS",
      "C. Larger payloads", "D. No cookies"], "B",
     ["Cybersecurity", "Cryptography"]),
    ("Cybersecurity", "theory", "medium",
     "Explain the difference between symmetric and asymmetric encryption.",
     None, None, ["Cybersecurity", "Cryptography"]),

    # ---------- System Design ----------
    ("System Design", "mcq", "medium",
     "Which strategy helps handle sudden traffic spikes in a web application?",
     ["A. Load balancing across multiple servers", "B. Removing indexes",
      "C. Using synchronous calls only", "D. Disabling caching"], "A",
     ["System Design", "Load Balancing"]),
    ("System Design", "theory", "medium",
     "How would you design a URL shortener? Walk through the key components.",
     None, None, ["System Design"]),

    # ---------- Aptitude ----------
    ("Aptitude", "mcq", "easy",
     "If a train travels 300 km in 3 hours, what is its average speed?",
     ["A. 90 km/h", "B. 100 km/h", "C. 110 km/h", "D. 120 km/h"], "B", ["Aptitude"]),
    ("Aptitude", "mcq", "medium",
     "What comes next in the series: 2, 6, 12, 20, 30, ?",
     ["A. 36", "B. 40", "C. 42", "D. 44"], "C", ["Aptitude", "Logical Reasoning"]),
    ("Aptitude", "mcq", "hard",
     "A bag contains 3 red and 5 blue balls. One ball is drawn at random. What is the probability it is red?",
     ["A. 1/8", "B. 3/8", "C. 5/8", "D. 3/5"], "B", ["Aptitude", "Quantitative Ability"]),

    # ---------- HR / Behavioral ----------
    ("Behavioral", "mcq", "easy",
     "In a STAR answer, what does the 'R' stand for?",
     ["A. Result", "B. Reaction", "C. Review", "D. Risk"], "A",
     ["Behavioral", "STAR"]),
    ("Behavioral", "scenario", "easy",
     "Tell me about a time you faced a conflict with a teammate. How did you resolve it?",
     None, None, ["Behavioral", "Conflict Resolution"]),
    ("Behavioral", "scenario", "medium",
     "Describe a situation where you had to meet a tight deadline with limited resources.",
     None, None, ["Behavioral", "Time Management"]),
    ("Behavioral", "rapid_fire", "easy",
     "What is your greatest strength?",
     None, None, ["Behavioral"]),
    ("HR", "mcq", "easy",
     "Which document typically lists an employee's key responsibilities?",
     ["A. Resume", "B. Job description", "C. Offer letter", "D. Payslip"], "B", ["HR"]),
    ("HR", "scenario", "medium",
     "An employee is underperforming. As a manager, how would you approach the conversation?",
     None, None, ["HR", "Performance Management"]),

    # ---------- Finance ----------
    ("Finance", "mcq", "easy",
     "Which financial statement shows a company's revenues and expenses over a period?",
     ["A. Balance sheet", "B. Income statement", "C. Cash flow statement", "D. Statement of changes"], "B",
     ["Finance", "Financial Statements"]),
    ("Finance", "mcq", "medium",
     "What does a positive cash flow from operations indicate?",
     ["A. The company is profitable on paper only",
      "B. The core business generates more cash than it consumes",
      "C. The company is bankrupt", "D. The company issued new shares"], "B",
     ["Finance", "Cash Flow"]),

    # ---------- Marketing ----------
    ("Marketing", "mcq", "easy",
     "Which 'P' of the marketing mix relates to pricing?",
     ["A. Product", "B. Price", "C. Place", "D. Promotion"], "B", ["Marketing"]),
    ("Marketing", "mcq", "medium",
     "What is a conversion rate in digital marketing?",
     ["A. Total visitors to a website",
      "B. The percentage of visitors who complete a desired action",
      "C. The number of ads shown", "D. The cost of a click"], "B",
     ["Marketing", "Digital Marketing"]),

    # ---------- Business Analytics ----------
    ("Business Analytics", "mcq", "easy",
     "Which metric measures how many customers stop using a product over a period?",
     ["A. Churn rate", "B. Conversion rate", "C. Click-through rate", "D. Retention rate"], "A",
     ["Business Analytics", "KPIs"]),
    ("Business Analytics", "theory", "medium",
     "How would you measure the impact of a new feature launch? What metrics would you track?",
     None, None, ["Business Analytics", "Metrics"]),

    # ---------- Case Study ----------
    ("Case Study", "mcq", "easy",
     "Which framework is commonly used to structure a market sizing case?",
     ["A. Top-down approach", "B. Random guess", "C. SWOT only", "D. No structure needed"], "A",
     ["Case Study", "Frameworks"]),
    ("Case Study", "scenario", "hard",
     "Estimate the number of cups of coffee sold in Mumbai on a typical day. Walk through your approach.",
     None, None, ["Case Study", "Quantitative Reasoning"]),
]


def get_bank_entries() -> list[dict]:
    return [
        {
            "domain": domain,
            "question_type": qtype,
            "difficulty": difficulty,
            "text": text,
            "options": options,
            "correct_answer": correct_answer,
            "skill_tags": skill_tags,
        }
        for domain, qtype, difficulty, text, options, correct_answer, skill_tags in QUESTION_BANK
    ]
